title: meteor-application-template-react
description: A template for quickly starting Meteor application development
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: https://github.com/JohnsonsList.io

gems:
  - jekyll-mentions
