title: meteor-application-template-react
description: Craigslist style of webiste for UH Manoa community
google_analytics:
show_downloads: false
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: https://https://github.com/JohnsonsList/JohnsonsList
gems:
  - jekyll-mentions
